[package]
name = "generate"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.57"
windows_macros = "0.31.0"
windows_gen = "0.31.0"
windows_reader = "0.31.0"
bindgen = "0.59.2"
pkg-config = "0.3.25"
