name: Weekly

on:
  schedule:
    - cron: '36 13 * * 4'

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.65", stable]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build --all-features -p audio -p audio-core -p audio-generator -p ste
